version: "3.9"

services:
  auth:
    build: .
    container_name: ${APP_NAME}
    restart: always
    depends_on:
      - auth_db
    env_file:
      - .env
    ports:
      - "${APP_PORT}:${APP_PORT}"

  auth_db:
    image: postgres:15
    container_name: auth_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - auth_pgdata:/var/lib/postgresql/data

volumes:
  auth_pgdata:
